### ISSUE TITLE
Attributes of Contact Point

### ISSUE THREAD

**Issue by maximepittomvils** [catalogue-of-services-isa/SDG-search-service-model#42]
**Concept**
Contact Point

**Description**
Which properties of Contact Point should be covered?

**Proposition**
We propose to align with CPOV: availability restriction, email, phone, opening hours. https://semiceu.github.io/CPOV/releases/2.00/#Contact%20Point

Are there other attributes you would like to see?

**Comment by anarosa-es** [comment]
Because this information is likely to change, I propose to use a webpage link where each competent authority can maintain the contact point information

**Comment by vintra73** [comment]
we agree with the proposal to use standard classes, nevertheless we highlight the need indicated by Annarosa to add workflows for managing their life cycle to the classes / attributes

**Comment by giorgialodi** [comment]
Just a suggestion from a semantic perspective: if you put simply a link to a URL of a web page, you do not model anything regarding possible elements of a contact point. So, questions like "to which email address  can I write in order to obtain information" cannot be answered. Not sure about the meaning of workflows. I mean mixing workflows and data is not easy at all, in semantic models (e.g., see the work on e-procurement where they intentionally did not want to model workflows).
My suggestion, from really a semantic perspective, is to do what it is currently done in DCAT-AP so that to create a unique, more standard and European way to manage contant points :)  Definitely linked to #41

**Comment by maximepittomvils** [comment]
As the Contact Point has been removed as decided under #41 , No need to define the attributes of the class.
